FROM openjdk:17-alpine
ENV TZ="Asia/Kolkata"
ADD target/sbioa-parent-service-0.0.1-SNAPSHOT.jar sbioa-parent-service-0.0.1-SNAPSHOT.jar
EXPOSE 8011
EXPOSE 8013
CMD java -jar sbioa-parent-service-0.0.1-SNAPSHOT.jar
