apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prove-backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-prove-backend