apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: lockourier-dev
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: registry.coherent.in/lockourier:24
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: nats-dev-mysql.coherent.in:3328
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: datasource-credentials
                  key: username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datasource-credentials
                  key: password
            - name: WORDPRESS_DB_NAME
              value: lockourier
      imagePullSecrets:
        - name: registry-regcred
