apiVersion: v1
kind: Service
metadata:
  labels:
    app: zenvo-portal-react
  name: zenvo-portal-react-svc
  namespace: tt2024-dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: zenvo-portal-react
