apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sbioa-sit-mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-sbioa-sit-mysql
