FROM openjdk:11.0.6-jre-slim
ENV TZ="Asia/Kolkata"
ADD target/LOSMasterManagementService-0.0.1-SNAPSHOT.jar LOSMasterManagementService-0.0.1-SNAPSHOT.jar
EXPOSE 6013
CMD java -jar LOSMasterManagementService-0.0.1-SNAPSHOT.jar
