FROM openjdk:17
ENV TZ="Asia/Kolkata"
ADD target/livewire_demo_springboot-0.0.1-SNAPSHOT.jar livewire_demo_springboot-0.0.1-SNAPSHOT.jar
EXPOSE 8093
CMD java -jar livewire_demo_springboot-0.0.1-SNAPSHOT.jar
