FROM openjdk:11.0.6-jre-slim
ENV TZ="Asia/Kolkata"
ADD target/DashboardManagementService-0.0.1-SNAPSHOT.jar DashboardManagementService-0.0.1-SNAPSHOT.jar
EXPOSE 7010
CMD java -jar DashboardManagementService-0.0.1-SNAPSHOT.jar