apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prove-mongodb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.coherent.in
    path: "/mnt/k8s-volume/nfs/k8s/prove/mongodb"
  mountOptions:
    - nfsvers=4.2