apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dms-dev-mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-dms-dev-mysql