@Library('gitops-data') _

def PROJECT_SCM_URL = "https://scm.coherent.in/coherent-user-manual/user-manual-portal.git"
def GITOPS_DATA_PROJECT_PATH = "umc/portal"
def PROJECT_NAME = util_extractProjectNameFromGitUrl("$PROJECT_SCM_URL")
def SONAR_ENVIRONMENTS = ["dev"]
def ENABLE_SONAR = false
def ENABLE_SONAR_QUALITY_GATE = false


template_react_node(
  "$PROJECT_SCM_URL",
  "$PROJECT_NAME",
  "$GITOPS_DATA_PROJECT_PATH",
  ENABLE_SONAR,
  ENABLE_SONAR_QUALITY_GATE,
  SONAR_ENVIRONMENTS
)