apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cms-dev-mysql
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.coherent.in
    path: "/mnt/k8s-volume/nfs/k8s/cms/dev/mysql"
  mountOptions:
    - nfsvers=4.2