apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cms-dev-mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
  volumeName: pv-cms-dev-mysql
