@Library('gitops-data') _

def PROJECT_SCM_URL = "https://scm.coherent.in/deal-management-system/dms-ml-service.git"
def GITOPS_DATA_PROJECT_PATH = "dms/dms-ml-service"
def PROJECT_NAME = util_extractProjectNameFromGitUrl("$PROJECT_SCM_URL")

template_python(
  "$PROJECT_SCM_URL",
  "$PROJECT_NAME",
  "$GITOPS_DATA_PROJECT_PATH"
)
