apiVersion: v1
kind: Service
metadata:
  labels:
    app: vitualqueue-backend
  name: vitualqueue-backend-svc
  namespace: tt2024-dev
spec:
  ports:
    - port: 8094
      protocol: TCP
      targetPort: 8094
  selector:
    app: vitualqueue-backend
