FROM openjdk:11.0.6-jre-slim
ENV TZ="Asia/Kolkata"
ADD target/UserManagementService-0.0.1-SNAPSHOT.jar UserManagementService-0.0.1-SNAPSHOT.jar
EXPOSE 6015
CMD java -jar UserManagementService-0.0.1-SNAPSHOT.jar
