FROM openjdk:11.0.6-jre-slim
ENV TZ="Asia/Kolkata"
ADD target/LOSLeadManagementService-0.0.1-SNAPSHOT.jar LOSLeadManagementService-0.0.1-SNAPSHOT.jar
EXPOSE 7011
CMD java -jar LOSLeadManagementService-0.0.1-SNAPSHOT.jar