FROM openjdk:11.0.6-jre-slim
ENV TZ="Asia/Kolkata"
ADD target/inventory-auth-service-0.0.1-SNAPSHOT.jar inventory-auth-service-0.0.1-SNAPSHOT.jar
EXPOSE 8011
CMD java -jar inventory-auth-service-0.0.1-SNAPSHOT.jar
