apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbioa-portal-react
  name: sbioa-portal-react-svc
  namespace: sbi-sit
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sbioa-portal-react
