@Library('gitops-data') _
template_angular(
    PROJECT_SCM_URL: 'https://your-git-repo.git',
    PROJECT_NAME: 'your-project',
    GITOPS_DATA_PROJECT_PATH: 'your-path',
    ANGULAR_VERSION: 'your-angular-version',
    NODE_IMAGE: 'your-node-image',
    ENABLE_SONAR: true,
    ENABLE_SONAR_QUALITY_GATE: true,
    SONAR_ENVIRONMENTS: ['dev']
)
