FROM openjdk:17-alpine
ENV TZ="Asia/Kolkata"
ADD target/primus-master-service-0.0.1-SNAPSHOT.jar primus-master-service-0.0.1-SNAPSHOT.jar
EXPOSE 8019
CMD java -jar primus-master-service-0.0.1-SNAPSHOT.jar