FROM openjdk:17

ENV TZ="Asia/Kolkata"

ADD target/deal-management-service-0.0.1-SNAPSHOT.jar deal-management-service-0.0.1-SNAPSHOT.jar

EXPOSE 8010

CMD java -jar deal-management-service-0.0.1-SNAPSHOT.jar
