apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: APPLICATION_NAME_HERE
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: Build-Notifications #Teams Channel
    notifications.argoproj.io/subscribe.on-sync-failed.teams: Build-Notifications #Teams Channel 
spec:
  project: default
  source:
    repoURL: https://github.com/Sarathkumarsoundarrajan/gitops-data.git
    targetRevision: master
    path: PROJECT_PATH_HERE
  destination: 
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
