apiVersion: v1
kind: Service
metadata:
  labels:
    app: hcp-portal
  name: hcp-portal-svc
  namespace: hcp-sit
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hcp-portal
