apiVersion: v1
kind: Service
metadata:
  labels:
    app: parent
  name: parent-svc
spec:
  ports:
    - port: 8011
      protocol: TCP
      targetPort: 8011
    - port: 8013
      protocol: TCP
      targetPort: 8013 
  selector:
    app: parent
