FROM openjdk:17-alpine
ENV TZ="Asia/Kolkata"
ADD target/primus-logic-service-0.0.1-SNAPSHOT.jar primus-logic-service-0.0.1-SNAPSHOT.jar
EXPOSE 8082
CMD java -jar primus-logic-service-0.0.1-SNAPSHOT.jar