@Library('gitops-data') _

def PROJECT_SCM_URL = "https://scm.coherent.in/taskflowpro/tfp-frontend-angular.git"
def GITOPS_DATA_PROJECT_PATH = "taskflowpro/portal"
def PROJECT_NAME = util_extractProjectNameFromGitUrl("$PROJECT_SCM_URL")
def SONAR_ENVIRONMENTS = ["dev","prod"]
def ENABLE_SONAR = false
def ENABLE_SONAR_QUALITY_GATE = false
def ANGULAR_VERSION = "@angular/cli"
def NODE_IMAGE = "node:19-alpine"

template_angular(
  "$PROJECT_SCM_URL",
  "$PROJECT_NAME",
  "$GITOPS_DATA_PROJECT_PATH",
  "$ANGULAR_VERSION",
  "$NODE_IMAGE",
  ENABLE_SONAR,
  ENABLE_SONAR_QUALITY_GATE,
  SONAR_ENVIRONMENTS
)