FROM openjdk:17-alpine
ENV TZ="Asia/Kolkata"
ADD target/sbioa-businesslogic-service-0.0.1-SNAPSHOT.jar sbioa-businesslogic-service-0.0.1-SNAPSHOT.jar
EXPOSE 8012
CMD java -jar sbioa-businesslogic-service-0.0.1-SNAPSHOT.jar
