@Library('gitops-data') _

def PROJECT_SCM_URL = "https://scm.coherent.in/aequitas/customer-service.git"
def GITOPS_DATA_PROJECT_PATH = "aequitas/customer"
// def PROJECT_NAME = util_extractProjectNameFromGitUrl("$PROJECT_SCM_URL")
// Convert project name to lowercase
def PROJECT_NAME = util_extractProjectNameFromGitUrl("$PROJECT_SCM_URL").toLowerCase()
def SONAR_ENVIRONMENTS = ["dev"]
def ENABLE_SONAR = false
def ENABLE_SONAR_QUALITY_GATE = false


template_maven_for_aequitas(
  "$PROJECT_SCM_URL",
  "$PROJECT_NAME",
  "$GITOPS_DATA_PROJECT_PATH",
  ENABLE_SONAR,
  ENABLE_SONAR_QUALITY_GATE,
  SONAR_ENVIRONMENTS
)