apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chd-portal-react-dev-application
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: Build-Notifications #Teams Channel
    notifications.argoproj.io/subscribe.on-sync-failed.teams: Build-Notifications #Teams Channel 
spec:
  project: default
  source:
    repoURL: https://scm.coherent.in/cicd/gitops-data.git
    targetRevision: master
    path: projects/chd/portal-react/k8s-config/dev
  destination: 
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
